-- SEED DO CASAMENTO NO SITIO --

INSERT INTO usuario (nome, cpf, email, senha, perfil) VALUES
    ('Administrador', '75688329134', 'admin@wedding.com', '$2b$12$rjIYNwPQkyi3Okmv8ryJSeIW40OhM1m4dmut1DBq.RgAm2c3aNHvC','Admin'),
    ('Cerimonial', '6357729145', 'recepcao@wedding.com', '$2b$12$QRawXobe3BwC9p409p6IgO18/Di0X5zMt.chBbmLQZFO7HnzASbj2','Comum');
INSERT INTO evento (nome, local, data_evento) VALUES
    ('Casamento no Sítio', 'Fenda do biquine', '2026-01-17');
INSERT INTO area (id_evento, nome_area, exige_vip) VALUES
    (1, 'Espaço do Buffet', 1),
    (1, 'Espaço de Danca', 1),
    (1, 'Espaço de Fotos', 1);
INSERT INTO usuario_evento (id_evento, id_usuario) VALUES
    (1, 1),
    (1, 2);
INSERT INTO convidado (id_evento, nome, status, categoria) VALUES(1, 'Stella', 'Confirmado','Geral'),
(1, 'Matteo', 'Cancelado','Vip'),
(1, 'Lucas Gabriel', 'Pendente','Vip'),
(1, 'Isis', 'Cancelado','Geral'),
(1, 'Samuel', 'Cancelado','Vip'),
(1, 'Fernanda', 'Cancelado','Geral'),
(1, 'Ana Laura', 'Cancelado','Vip'),
(1, 'Samuel', 'Confirmado','Vip'),
(1, 'Nicolas', 'Pendente','Vip'),
(1, 'Erick', 'Cancelado','Vip'),
(1, 'Raquel', 'Confirmado','Vip'),
(1, 'Laís', 'Cancelado','Vip'),
(1, 'Benício', 'Confirmado','Geral'),
(1, 'Esther', 'Cancelado','Vip'),
(1, 'Vitória', 'Cancelado','Geral'),
(1, 'Oliver', 'Confirmado','Geral'),
(1, 'Valentina', 'Confirmado','Geral'),
(1, 'João Lucas', 'Confirmado','Geral'),
(1, 'Júlia', 'Cancelado','Vip'),
(1, 'Pedro Henrique', 'Cancelado','Geral'),
(1, 'Calebe', 'Cancelado','Vip'),
(1, 'Ana Vitória', 'Cancelado','Vip'),
(1, 'Júlia', 'Pendente','Vip'),
(1, 'Manuela', 'Cancelado','Geral'),
(1, 'Renan', 'Confirmado','Vip'),
(1, 'Ester', 'Pendente','Vip'),
(1, 'Maria Eduarda', 'Confirmado','Geral'),
(1, 'Milena', 'Pendente','Vip'),
(1, 'Davi Luiz', 'Cancelado','Geral'),
(1, 'Maria Isis', 'Cancelado','Vip'),
(1, 'Leandro', 'Cancelado','Vip'),
(1, 'Eloá', 'Pendente','Vip'),
(1, 'Isabel', 'Pendente','Vip'),
(1, 'Murilo', 'Cancelado','Vip'),
(1, 'Ana Vitória', 'Pendente','Geral'),
(1, 'Pedro Lucas', 'Pendente','Vip'),
(1, 'Ísis', 'Pendente','Vip'),
(1, 'Pietro', 'Confirmado','Geral'),
(1, 'Juan', 'Pendente','Vip'),
(1, 'Marcela', 'Pendente','Geral'),
(1, 'Thales', 'Pendente','Vip'),
(1, 'Gael', 'Cancelado','Vip'),
(1, 'Fernando', 'Cancelado','Vip'),
(1, 'Thiago', 'Pendente','Vip'),
(1, 'Luiz Felipe', 'Cancelado','Geral'),
(1, 'Otto', 'Pendente','Geral'),
(1, 'Fernanda', 'Confirmado','Geral'),
(1, 'Milena', 'Confirmado','Vip'),
(1, 'Isis', 'Confirmado','Vip'),
(1, 'Asafe', 'Pendente','Vip'),
(1, 'Pedro', 'Cancelado','Vip'),
(1, 'Thiago', 'Cancelado','Vip'),
(1, 'Eloá', 'Cancelado','Vip'),
(1, 'Catarina', 'Cancelado','Geral'),
(1, 'Vitória', 'Confirmado','Geral'),
(1, 'Guilherme', 'Cancelado','Geral'),
(1, 'Felipe', 'Confirmado','Geral'),
(1, 'Maria Alice', 'Pendente','Geral'),
(1, 'Mathias', 'Confirmado','Vip'),
(1, 'Ravi Lucca', 'Pendente','Geral'),
(1, 'Alana', 'Cancelado','Geral'),
(1, 'Emanuelly', 'Cancelado','Geral'),
(1, 'Lorena', 'Pendente','Geral'),
(1, 'Lunna', 'Cancelado','Vip'),
(1, 'Levi', 'Confirmado','Geral'),
(1, 'Luna', 'Cancelado','Geral'),
(1, 'Ana', 'Cancelado','Geral'),
(1, 'Ana Liz', 'Cancelado','Vip'),
(1, 'Joaquim', 'Pendente','Geral'),
(1, 'Maria Eduarda', 'Pendente','Geral'),
(1, 'Lara', 'Pendente','Geral'),
(1, 'Jade', 'Confirmado','Vip'),
(1, 'Ravi Lucca', 'Pendente','Vip'),
(1, 'Maya', 'Pendente','Geral'),
(1, 'Maria Vitória', 'Confirmado','Geral'),
(1, 'Oliver', 'Confirmado','Vip'),
(1, 'Bruno', 'Cancelado','Vip'),
(1, 'Cauã', 'Cancelado','Geral'),
(1, 'Emilly', 'Cancelado','Vip'),
(1, 'Stephany', 'Confirmado','Vip'),
(1, 'Ana Lívia', 'Cancelado','Geral'),
(1, 'Manuela', 'Pendente','Vip'),
(1, 'Antônio', 'Confirmado','Vip'),
(1, 'Benício', 'Confirmado','Vip'),
(1, 'Josué', 'Confirmado','Vip'),
(1, 'Mathias', 'Pendente','Vip'),
(1, 'Luara', 'Confirmado','Geral'),
(1, 'Davi Luiz', 'Pendente','Vip'),
(1, 'Allana', 'Confirmado','Vip'),
(1, 'Alana', 'Pendente','Geral'),
(1, 'Vinícius', 'Confirmado','Vip'),
(1, 'Otto', 'Cancelado','Geral'),
(1, 'Juan', 'Pendente','Geral'),
(1, 'Antonella', 'Confirmado','Geral'),
(1, 'Guilherme', 'Cancelado','Geral'),
(1, 'Maria Luiza', 'Confirmado','Geral'),
(1, 'Rafael', 'Confirmado','Geral'),
(1, 'Mariane', 'Confirmado','Vip'),
(1, 'Luiza', 'Pendente','Vip'),
(1, 'Catarina', 'Pendente','Geral');
INSERT INTO acesso_area (id_convidado, id_area, data_hora_acesso) VALUES
    (1, 1, NOW()),
    (1, 2, NOW()),
    (1, 3, NOW());
INSERT INTO checkin (id_convidado, id_usuario, id_evento, data_hora) VALUES
    (1, 1, 1, NOW()),
    (2, 1, 1, NOW()),
    (3, 1, 1, NOW());
    